# Generated by Django 4.2.7 on 2024-01-23 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Data', '0002_cryptodata_15min_forexdata_15min_stockdata_15min'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('day_trading', models.BooleanField()),
                ('long_term_invest', models.BooleanField()),
                ('symbol', models.CharField(max_length=50)),
                ('sell', models.BooleanField()),
                ('buy', models.BooleanField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
