# Generated by Django 4.2.7 on 2024-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_stockordercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='current_invest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
