# Generated by Django 4.2.7 on 2023-12-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_stockdata_previous_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.FloatField(null=True),
        ),
    ]
