# Generated by Django 4.2.7 on 2024-01-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_accountbalance_current_invest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='current_invest',
            new_name='stock_amount',
        ),
    ]
