# Generated by Django 4.2.7 on 2023-12-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_alter_stockdata_close_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
