# Generated by Django 4.2.7 on 2023-12-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_delete_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('current_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField(null=True)),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('percent_change', models.FloatField()),
                ('change', models.FloatField()),
                ('previous_close', models.FloatField(default=0)),
            ],
        ),
    ]
