# Generated by Django 4.2.7 on 2023-12-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_stockdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
